### ISSUE TITLE
Apache library files error is not allowing HuskSync plugin to work with Magma jars

### ISSUE THREAD

**Issue by Deathwolf01** [magmamaintained/Magma-1.18.2#4]
**Minecraft Version:** {Minecraft version}
1.18.2

**Forge Version:** {Forge version. *Version number, not latest/rb*}
40.2.14

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://mclo.gs/7nNScAU

**Steps to Reproduce:**
 1. Delete all server files
 2. Install Magma jar, Add Plugin folder with HuskSync plugin and the working HuskSync config file from a Paper server
 3. Start server, and see the error appear when it tries to load apache files to connect to another Redis 6 server. Reproducing these same steps on a standard Paper jar server works completely fine with HuskSync using the same plugin jar and config file.

**Description of issue:**

Whenever I run the server with the correct working HuskSync configuration on a Magma server, I get this error below with apache when it loads the libraries for the plugin. I have tried to manually copy and paste the apache folder from a working library on a Paper server into the Magma library but no luck, I get missing apache files crashes on start up if I mess with apache library folder.

So far this HuskSync plugin doesn't work with any Magma jars I've tried. I've tried Magma-1.18.2-40.2.10-5012a7f4-server, Magma-1.18.2-40.2.10-5fc5c9e8-server.jar, and magma-1.18.2-40.2.14-1f43a91-server.
Error:
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/commons/pool2/impl/GenericObjectPoolConfig

**Additional Info from HuskSync Dev:**
HuskSync uses a paper class loader and so the paper impl should load the jars.
If the server doesn’t implement paper plugins api, then HuskSync also provides a spigot plugin that should load the libraries via the Spigot resource library loader

**Comment by TonimatasDEV** [comment]
> **Minecraft Version:** {Minecraft version} 1.18.2
> 
> **Forge Version:** {Forge version. _Version number, not latest/rb_} 40.2.14
> 
> **Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report} https://mclo.gs/7nNScAU
> 
> **Steps to Reproduce:**
> 
> 1. Delete all server files
> 2. Install Magma jar, Add Plugin folder with HuskSync plugin and the working HuskSync config file from a Paper server
> 3. Start server, and see the error appear when it tries to load apache files to connect to another Redis 6 server. Reproducing these same steps on a standard Paper jar server works completely fine with HuskSync using the same plugin jar and config file.
> 
> **Description of issue:**
> 
> Whenever I run the server with the correct working HuskSync configuration on a Magma server, I get this error below with apache when it loads the libraries for the plugin. I have tried to manually copy and paste the apache folder from a working library on a Paper server into the Magma library but no luck, I get missing apache files crashes on start up if I mess with apache library folder.
> 
> So far this HuskSync plugin doesn't work with any Magma jars I've tried. I've tried Magma-1.18.2-40.2.10-5012a7f4-server, Magma-1.18.2-40.2.10-5fc5c9e8-server.jar, and magma-1.18.2-40.2.14-1f43a91-server. Error: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/commons/pool2/impl/GenericObjectPoolConfig
> 
> **Additional Info from HuskSync Dev:** HuskSync uses a paper class loader and so the paper impl should load the jars. If the server doesn’t implement paper plugins api, then HuskSync also provides a spigot plugin that should load the libraries via the Spigot resource library loader

It works in normal Spigot?

**Comment by Deathwolf01** [comment]
Yes, it works without issues on a Paper server running 1.18.2 on Build 388

**Comment by TonimatasDEV** [comment]
> Yes, it works without issues on a Paper server running 1.18.2 on Build 388

Test it on Spigot, magma doesn't support paper at the moment.

**Comment by Deathwolf01** [comment]
> > Yes, it works without issues on a Paper server running 1.18.2 on Build 388
> 
> Test it on Spigot, magma doesn't support paper at the moment. Maybe paper will add the library the plugins needs.

It seems to also work on 1.18.2 Spigot Jar downloaded from Spigot's website. It successfully connects to the MYSQL and Redis databases. Using a copied and pasted config folder and jar from the fresh installed magma server.
https://mclo.gs/9rAqokB

**Comment by TonimatasDEV** [comment]
I need to apply the 1.20.1 patch to this version

**Comment by Deathwolf01** [comment]
Hello, I'm curious if the latest 1.18.2 40.2.17 jar may have reverted the libraries fixes from the previous magma-1.18.2-40.2.14-48b7188-server.jar? On the latest jar update, The husksync plugin I am trying shows an error that it cannot find libraries/libraries.txt, and it won't create its own config folders. But the latest 40.2.10 magma jar still works, just without the redis server part because of libraries issue. No rush on it, I'm just curious if I can get this plugin working on magma.

> [22Jan2024 04:20:42.390] [Server thread/INFO] [org.magmafoundation.magma.Magma/]: [HuskSync] Loading 4 libraries... please wait
[22Jan2024 04:20:42.391] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/HuskSync-Plugin-3.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: java.io.FileNotFoundException: libraries/libraries.txt (No such file or directory)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:142) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:323) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:230) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:909) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:263) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: libraries/libraries.txt (No such file or directory)
	at org.bukkit.plugin.java.LibraryLoader.magmaLibs(LibraryLoader.java:180) ~[?:?]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:46) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[?:?]
	... 7 more
Caused by: java.io.FileNotFoundException: libraries/libraries.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?]
	at java.io.FileReader.<init>(FileReader.java:60) ~[?:?]
	at org.bukkit.plugin.java.LibraryLoader.magmaLibs(LibraryLoader.java:178) ~[?:?]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:46) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[?:?]
	... 7 more
